const routes = {
  HOME: process.env.PUBLIC_URL + "/",
  DASHBOARD: process.env.PUBLIC_URL + "/dashboard",
  NOTIFICATIONLIST: process.env.PUBLIC_URL + "/notification-list",
  MERCHANTSLIST: process.env.PUBLIC_URL + "/merchantslist",
  MERCHANTSCAMPAIGNS: process.env.PUBLIC_URL + "/merchant-campaigns",
  CAMPAIGN: process.env.PUBLIC_URL + "/campaign",
  TASKVIEW: process.env.PUBLIC_URL + "/taskview",
  INFLUENCERVIEW: process.env.PUBLIC_URL + "/influencer-view",
  INFLUENCER: process.env.PUBLIC_URL + "/influencer",
  INFLUENCERPROFILE: process.env.PUBLIC_URL + "/influencer-profile",
  CAMPAIGNVIEW: process.env.PUBLIC_URL + "/campaign-view",
  CREATETASK: process.env.PUBLIC_URL + "/create-task",
  UPDATETASK: process.env.PUBLIC_URL + "/update-task",
  CREATCAMPAIGN: process.env.PUBLIC_URL + "/create-campaign",
  UPDATECAMPAIGN: process.env.PUBLIC_URL + "/update-campaign",
  CREATTASKSTEP: process.env.PUBLIC_URL + "/create-task-step",
  UPDATETASKSTEP: process.env.PUBLIC_URL + "/update-task-step",
  SIGNIN: process.env.PUBLIC_URL + "/signin",
  SIGNUP: process.env.PUBLIC_URL + "/signup",
  FORGOTPASSWORD: process.env.PUBLIC_URL + "/forgot-password",
  RESETPASSWORD: process.env.PUBLIC_URL + "/reset_password",
  MERCHANTPROFILE: process.env.PUBLIC_URL + "/merchant-profile",
  VIEWMERCHANTPROFILE: process.env.PUBLIC_URL + "/view-merchant-profile",
  CAMPAIGNLIST: process.env.PUBLIC_URL + "/campaignList",
  SETTING: process.env.PUBLIC_URL + "/setting",
};

export default routes;
